---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata
  generateName linter-pipeline-run-
spec:
  pipelineRef:
    name: linter-pipeline
  workspaces
    - name: shared-workspace
      volumeClaimTemplate:
        spec
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
